### ISSUE TITLE
KIF 3.2 should be used

### ISSUE THREAD

**Issue by jshier** [IndieGoGo/KIF-Kiwi#4]
KIF 3.2 adds some nice gesture methods. KIF-Kiwi should update its KIF dependency to use this latest version.

**Comment by gogogadget** [comment]
sounds good, thank you @jshier

**Comment by paulz** [comment]
added 3.2 on master, so you can try to use in your Podfile:
```
    pod 'KIF-Kiwi',                 # write KIF tests Kiwi style
        :git => 'https://github.com/IndieGoGo/KIF-Kiwi.git'
```

**Comment by paulz** [comment]
fixed in https://github.com/IndieGoGo/KIF-Kiwi/releases/tag/0.2.4
